# Generated by Django 5.2.13 on 2026-04-18 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('slot', models.CharField(choices=[('sla', 'SLA Page'), ('contact', 'Contact Page'), ('about', 'About Page'), ('navbar', 'Navbar'), ('custom', 'Custom Page')], default='custom', max_length=20)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text / Rich Text'), ('card', 'Card'), ('image', 'Image'), ('dropdown', 'Accordion / Dropdown'), ('checkbox', 'Checklist'), ('divider', 'Divider'), ('heading', 'Heading'), ('table', 'Table')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.JSONField(default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
